version: '2'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    working_dir: /var/www
    ports:
      - "9876:9876"
      - "5022:22"
    privileged: true
    volumes:
      - ../:/var/www

#  Chrome:
#    image: selenium/standalone-chrome-debug:3.11.0-californium
#    container_name: Chrome
#    ports:
#      - 4444:4444
#      - 15900:5900

#volumes:
#  pgsql-data:
#    driver: local
